name: Run PHP Script with Secrets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_HOSTW: ${{ secrets.DB_HOSTW }}
      DB_NAMEW: ${{ secrets.DB_NAMEW }}
      DB_PASSW: ${{ secrets.DB_PASSW }}
      DB_USERW: ${{ secrets.DB_USERW }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PHP script
        run: php config.php

      - name: Debug environment variables
        run: |
          echo "DB_HOSTW=$DB_HOSTW"
          echo "DB_NAMEW=$DB_NAMEW"
          echo "DB_USERW=$DB_USERW"
          echo "DB_PASSW=$DB_PASSW"
